version: "3"

services:
  app:
    build: .
    restart: always
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 40s ./.docker/entrypoint-dev.sh
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
  postgres:
    build: .docker/postgres
    container_name: postgresDB
    ports:
      - 5432:5432
    restart: always
    tty: true
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOSTNAME: ${DATABASE_HOSTNAME}
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
